theme: jekyll-theme-midnight

title: Tore Aurstad
description: "Developer notes, lectures & demos — .NET, AI, MCP and more."
url: "https://toreaurstadboss.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge
